Aegisub/Aegisub

src/subtitles_provider.cpp
Related bug: #1805 "Attached Font Not Working".
This fix alone is only one part of the deal apparently: Aegisub's csri/xy-vsfilter-aegisub##.dll (May 1, 2014) also needs an update because it doesn't use the attached fonts, whereas the official xy-VSFilter 3.0.0.306 dll (copied to Aegisub/csri directory and selected as a primary renderer) is showing the fonts correctly.
=> Pass all font attachments to font renderer

src/dialog_style_editor.cpp
People tend to use `270` rotation angle not knowing|remembering it's equal to `-90`.
Fixes #1832.
=> Style editor: accept -360..360deg range

libaegisub/Makefile
`-fPIC` is only useful when building shared libraries.
=> Don't use -fPIC

src/video_provider_ffmpegsource.cpp
FFMS2 originally would automatically attempt to guess the color space if not manually specified, but this was removed in ffms/ffms2@7c2e08109d6097d5a644722ca7cfafa002203457 and Aegisub never adapted to the change.
Courtesy of duplex
=> Properly set colorspace when loading video

automation/Makefile, libaegisub/Makefile, packages/desktop/Makefile, src/Makefile, vendor/luabins/Makefile
Wildcard result order depends on filesystem stuff.
This matters for lunix packaging systems etc.
=> build: sort wildcard results for repeatable builds

src/utils.cpp
icu was just updated to 59.1 in Arch Linux' repositories, breaking aegisub in the process. It builds fine again with this additional header.
=> Fix compilation against icu 59.1

src/dialog_about.cpp, src/version.cpp
The build date is largely irrelevant and prevents reproducible builds.
Make it optional.
=> dialog_about: only include build date with credit

.gitmodules
we already removed its folder ( vendor/fontconfig ), so we should remove it from the actual submodule list as well
=> remove fontconfig submodule

src/command/edit.cpp
Joining lines as karaoke was broken since at least 2013: http://forum.aegisub.org/viewtopic.php?f=13&t=65820
Let's say we have three lines, each spanning 0.3s:
1. Ku
2. ru
3. shii
Before the change, joining these lines as karaoke resulted in:
```
Ku{\k0}ru{\k0}shii
```
After the change, joining these lines as karaoke results in:
```
{\k30}Ku{\k30}ru{\k30}shii
```
=> Fix joining as karaoke

automation/v4-docs/misc.txt, src/auto4_lua.cpp
This exposes `get_audio_selection` that returns a tuple containing the start and end position on the waveform selection.
My use case is to play the active audio selection through mpv at slower tempo. Having such API will let me replay single words without committing.
=> Add support for reading waveform selection in LUA

libaegisub/Makefile, src/Makefile, tests/Makefile, vendor/luabins/Makefile
$(subst .c,.o,...) replaces '.c' with '.o' everywhere in pathnames. For
example, renaming the "Aegisub" folder to "Aegisub.cool" will make the
build system generate "Aegisub.oool/.../.o" objects.
https://www.gnu.org/software/make/manual/make.html#Text-Functions
=> Makefiles: replace the use of subst macro with patsubst

po/it.po
There is a little typo in the Italian localization and because of the place where it is located I can do nothing but to see it everytime I open an MKV file with Aegisub. This patch fixes it.
=> Fix typo in the Italian localization

src/search_replace_engine.cpp
After boostorg/range@69409ed63a9e1 build fails. See [Aegisub-3.2.2 error log](https://ptpb.pw/fjhH).
Sorry, I can't test `master` because it doesn't build on FreeBSD.
=> Unbreak build against Boost 1.68

build/fribidi/fribidi.vcxproj
http://fribidi.org/download/fribidi-0.19.6.tar.bz2 gives "domain expired".
=> Fix fribidi download link

src/spellchecker.cpp, src/subs_edit_ctrl.cpp
Fix crash on right click due to no spell checker.
See: #131
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935724#15
https://github.com/wangqr/Aegisub/commit/0b8b286767bf796ecfc993c38c4ad14091703162#diff-64304e039535719d12a4a36d333a555c
A similar patch is going to be included in the official Debian packages.
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=935724#25
=> Fix crash on right click due to no spell checker

configure.ac
Add missing AM_GNU_GETTEXT_VERSION macro.
https://web.archive.org/web/20160729163303/http://devel.aegisub.org/ticket/1914
This patch is present in the official Mageia packages.
http://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/SRPMS/core/release/aegisub-3.2.2-14.git20180730.7.mga8.src.rpm
=> Add missing AM_GNU_GETTEXT_VERSION macro

Makefile.inc.in, configure.ac, libaegisub/unix/path.cpp, src/Makefile, src/aegisublocale.cpp
Configuring with `--enable-appimage` will set certain relocations that allow Aegisub to be used in a portable way on Linux. Nothing changes if `--enable-appimage` was not given, with one exception: the configured locale path will now be added explicitly to the search path if the OS isn't Windows or Mac and if `--enable-appimage` wasn't set.
A portable build will look for automation files and localizations in the same path as the binary is stored.
Here's an AppImage I built using these changes:
https://drive.google.com/file/d/18xHvZBpwqzYy9zKCBoZQSCX2RdCGAn-c/view?usp=sharing
Here's the build script: https://gist.github.com/darealshinji/9bc9689394b9bd8c6ea6d5f9b1732617
=> Option to create portable builds on Linux

src/colour_button.cpp, src/subtitles_provider_libass.cpp, src/video_frame.cpp, src/video_provider_dummy.cpp
Fixes for Boost 1.69.0.
https://github.com/Aegisub/Aegisub/issues/93
https://github.com/wangqr/Aegisub/commit/bb1f66a01f6e4661ab9c6610c5c2eee67bd0bd61
https://github.com/gentoo/gentoo/blob/e2087ed19aa3327eb00833f64e5bf315d43816fa/media-video/aegisub/files/3.2.2_p20160518/aegisub-3.2.2_p20160518-fix-boost170-build.patch
This patch is present in the official Gentoo packages.
https://github.com/gentoo/gentoo/blob/be23ef21ed508c8e580f3ee8f302ce2abc5c3fbe/media-video/aegisub
Similar patches are present in the official RPM Fusion (Fedora) and openSUSE packages.
http://download1.rpmfusion.org/free/fedora/development/rawhide/source/SRPMS/aegisub-3.2.2-15.20180710.git524c611.fc31.src.rpm
http://download.opensuse.org/repositories/openSUSE:/Factory/standard/src/aegisub-3.2.2+git20180710-3.6.src.rpm
=> Fixes for Boost 1.69.0

src/subs_edit_ctrl.cpp
Aegisub crashes immediately after selecting any language from the end of the list (above the 100th position).
This is because it can support no more than 100 languages.
This patch extends this limit up to 1000 languages (locales).
Fixes #131
---
Test results from my system.
Number of dictionaries:
```
$ find /usr/share/myspell/ -xtype f -iname '*.dic' -exec printf %.0s. {} + | wc -m
242
```
Number of thesaurus:
```
$ find /usr/share/myspell/ -xtype f -iname '*.aff' -exec printf %.0s. {} + | wc -m
242
```
Number of languages:
```
$ cat <( find /usr/share/myspell/ -xtype f -iname '*.dic' -exec printf %.0s. {} + | wc -m ) <( find /usr/share/myspell/ -xtype f -iname '*.aff' -exec printf %.0s. {} + | wc -m ) | sort -nr | head -n 1
242
```
Number of locales:
```
locale -a | wc -l
791
```
--- …
=> Fix crashing when picking language

configure.ac
Building Aegisub on Ubuntu just with `./configure && make` makes the check succeed, but if I use `debuild` to build a Debian package the OpenAL check will fail.
Here's the part from config.log:
```
configure:11659: checking whether OpenAL works
configure:11689: g++ -o conftest  -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -pipe -g -std=c++11 -Wno-c++11-narrowing -Wno-unused-local-typedefs -O3  -I/usr/include/AL  conftest.cpp -ldl -lm  -lopenal >&5
configure:11689: $? = 0
configure:11689: ./conftest
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection terminated
AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
configure:11689: $? = 1
configure: program exited with status 1
```
=> don't be too pedantic on the OpenAL checks

src/video_display.cpp
In 888be0607fdfc2ed7801fd67f46ab4f98257d419 some changes have been made to video_display.cpp which causes infinite recursion: the video display enables video/tool/cross tool when running VideoDisplay::Render() for the first time.
But when setting up the tool, the video box size is changed, which calls VideoDisplay::Render() again. So we need to set the tool BEFORE it modifies the box by "AddSeparator".
Fix wangqr/Aegisub#21
Co-authored-by: Charlie Jiang <cqjjjzr@126.com>
=> fix: infinite recursion when loading video
